#!/usr/bin/env sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

STAGED=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(ts|tsx|js|jsx|mjs|cjs)$' || true)

if [ -n "$STAGED" ]; then
  echo "$STAGED" | xargs npx eslint --fix
  echo "$STAGED" | xargs git add
fi